[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/billing-success"
  to = "/billing.html?success=true"
  status = 200

[[redirects]]
  from = "/billing-cancel"  
  to = "/billing.html?canceled=true"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
